// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Mutation struct {
}

type NewPlayer struct {
	PlayerID string     `json:"playerID"`
	Name     string     `json:"name"`
	Type     PlayerType `json:"type"`
	TeamID   *string    `json:"teamID,omitempty"`
}

type NewRoom struct {
	RoomID   string     `json:"roomID"`
	HostID   string     `json:"hostID"`
	HostName string     `json:"hostName"`
	HostType PlayerType `json:"hostType"`
	TeamID   *string    `json:"teamID,omitempty"`
}

type Player struct {
	ID     string     `json:"id"`
	Name   string     `json:"name"`
	Type   PlayerType `json:"type"`
	TeamID *string    `json:"teamID,omitempty"`
}

type Query struct {
}

type Room struct {
	ID        string     `json:"id"`
	HostID    string     `json:"hostID"`
	Status    RoomStatus `json:"status"`
	GameID    *string    `json:"gameID,omitempty"`
	Players   []*Player  `json:"players"`
	CreatedAt time.Time  `json:"createdAt"`
}

type StartGameInput struct {
	RoomID string `json:"roomID"`
	GameID string `json:"gameID"`
}

type PlayerType string

const (
	PlayerTypeHumano PlayerType = "HUMANO"
	PlayerTypeBot    PlayerType = "BOT"
)

var AllPlayerType = []PlayerType{
	PlayerTypeHumano,
	PlayerTypeBot,
}

func (e PlayerType) IsValid() bool {
	switch e {
	case PlayerTypeHumano, PlayerTypeBot:
		return true
	}
	return false
}

func (e PlayerType) String() string {
	return string(e)
}

func (e *PlayerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerType", str)
	}
	return nil
}

func (e PlayerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoomStatus string

const (
	RoomStatusAberta    RoomStatus = "ABERTA"
	RoomStatusEmPartida RoomStatus = "EM_PARTIDA"
	RoomStatusFechada   RoomStatus = "FECHADA"
)

var AllRoomStatus = []RoomStatus{
	RoomStatusAberta,
	RoomStatusEmPartida,
	RoomStatusFechada,
}

func (e RoomStatus) IsValid() bool {
	switch e {
	case RoomStatusAberta, RoomStatusEmPartida, RoomStatusFechada:
		return true
	}
	return false
}

func (e RoomStatus) String() string {
	return string(e)
}

func (e *RoomStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomStatus", str)
	}
	return nil
}

func (e RoomStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoomStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoomStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
