// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	User *User `json:"user"`
}

type CreateRoomInput struct {
	HostID string `json:"hostId"`
}

type Friendship struct {
	RequesterID string           `json:"requesterId"`
	AddresseeID string           `json:"addresseeId"`
	Status      FriendshipStatus `json:"status"`
	CreatedAt   time.Time        `json:"createdAt"`
	UpdatedAt   time.Time        `json:"updatedAt"`
}

type JoinRoomInput struct {
	RoomID string `json:"roomId"`
	UserID string `json:"userId"`
}

type LeaveRoomInput struct {
	RoomID string `json:"roomId"`
	UserID string `json:"userId"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Player struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Type     PlayerType `json:"type"`
	Sequence int32      `json:"sequence"`
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RemoveFriendInput struct {
	UserID   string `json:"userId"`
	FriendID string `json:"friendId"`
}

type RespondFriendRequestInput struct {
	RequesterID string `json:"requesterId"`
	AddresseeID string `json:"addresseeId"`
}

type Room struct {
	ID        string        `json:"id"`
	HostID    string        `json:"hostId"`
	Players   []*RoomPlayer `json:"players"`
	Status    RoomStatus    `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
}

type RoomPlayer struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type SendFriendRequestInput struct {
	RequesterID string `json:"requesterId"`
	AddresseeID string `json:"addresseeId"`
}

type StartGameInput struct {
	RoomID string `json:"roomId"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type UserStats struct {
	UserID string `json:"userId"`
	Games  int32  `json:"games"`
	Wins   int32  `json:"wins"`
	Elo    int32  `json:"elo"`
}

type FriendshipStatus string

const (
	FriendshipStatusPending  FriendshipStatus = "PENDING"
	FriendshipStatusAccepted FriendshipStatus = "ACCEPTED"
	FriendshipStatusRejected FriendshipStatus = "REJECTED"
)

var AllFriendshipStatus = []FriendshipStatus{
	FriendshipStatusPending,
	FriendshipStatusAccepted,
	FriendshipStatusRejected,
}

func (e FriendshipStatus) IsValid() bool {
	switch e {
	case FriendshipStatusPending, FriendshipStatusAccepted, FriendshipStatusRejected:
		return true
	}
	return false
}

func (e FriendshipStatus) String() string {
	return string(e)
}

func (e *FriendshipStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FriendshipStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FriendshipStatus", str)
	}
	return nil
}

func (e FriendshipStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FriendshipStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FriendshipStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlayerType string

const (
	PlayerTypeHuman PlayerType = "HUMAN"
	PlayerTypeBot   PlayerType = "BOT"
)

var AllPlayerType = []PlayerType{
	PlayerTypeHuman,
	PlayerTypeBot,
}

func (e PlayerType) IsValid() bool {
	switch e {
	case PlayerTypeHuman, PlayerTypeBot:
		return true
	}
	return false
}

func (e PlayerType) String() string {
	return string(e)
}

func (e *PlayerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerType", str)
	}
	return nil
}

func (e PlayerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoomStatus string

const (
	RoomStatusOpen   RoomStatus = "OPEN"
	RoomStatusInGame RoomStatus = "IN_GAME"
	RoomStatusClosed RoomStatus = "CLOSED"
)

var AllRoomStatus = []RoomStatus{
	RoomStatusOpen,
	RoomStatusInGame,
	RoomStatusClosed,
}

func (e RoomStatus) IsValid() bool {
	switch e {
	case RoomStatusOpen, RoomStatusInGame, RoomStatusClosed:
		return true
	}
	return false
}

func (e RoomStatus) String() string {
	return string(e)
}

func (e *RoomStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomStatus", str)
	}
	return nil
}

func (e RoomStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoomStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoomStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
