// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateRoomInput struct {
	RoomID   string `json:"roomId"`
	HostID   string `json:"hostId"`
	HostName string `json:"hostName"`
}

type JoinRoomInput struct {
	RoomID     string `json:"roomId"`
	PlayerID   string `json:"playerId"`
	PlayerName string `json:"playerName"`
}

type LeaveRoomInput struct {
	RoomID   string `json:"roomId"`
	PlayerID string `json:"playerId"`
}

type Mutation struct {
}

type Player struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Type     PlayerType `json:"type"`
	Sequence int32      `json:"sequence"`
}

type Query struct {
}

type Room struct {
	ID        string     `json:"id"`
	HostID    string     `json:"hostId"`
	Players   []*Player  `json:"players"`
	Status    RoomStatus `json:"status"`
	GameID    *string    `json:"gameId,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
}

type StartGameInput struct {
	RoomID string `json:"roomId"`
}

type PlayerType string

const (
	PlayerTypeHuman PlayerType = "HUMAN"
	PlayerTypeBot   PlayerType = "BOT"
)

var AllPlayerType = []PlayerType{
	PlayerTypeHuman,
	PlayerTypeBot,
}

func (e PlayerType) IsValid() bool {
	switch e {
	case PlayerTypeHuman, PlayerTypeBot:
		return true
	}
	return false
}

func (e PlayerType) String() string {
	return string(e)
}

func (e *PlayerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerType", str)
	}
	return nil
}

func (e PlayerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoomStatus string

const (
	RoomStatusOpen   RoomStatus = "OPEN"
	RoomStatusInGame RoomStatus = "IN_GAME"
	RoomStatusClosed RoomStatus = "CLOSED"
)

var AllRoomStatus = []RoomStatus{
	RoomStatusOpen,
	RoomStatusInGame,
	RoomStatusClosed,
}

func (e RoomStatus) IsValid() bool {
	switch e {
	case RoomStatusOpen, RoomStatusInGame, RoomStatusClosed:
		return true
	}
	return false
}

func (e RoomStatus) String() string {
	return string(e)
}

func (e *RoomStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomStatus", str)
	}
	return nil
}

func (e RoomStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoomStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoomStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
