// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type EventPayload interface {
	IsEventPayload()
}

type AuthPayload struct {
	User *User `json:"user"`
}

type CardDealtEventPayload struct {
	PlayerID string    `json:"playerId"`
	Card     *GameCard `json:"card"`
}

func (CardDealtEventPayload) IsEventPayload() {}

type CardPlayedEventPayload struct {
	PlayerID string    `json:"playerId"`
	Card     *GameCard `json:"card"`
}

func (CardPlayedEventPayload) IsEventPayload() {}

type CreateRoomInput struct {
	HostID string `json:"hostId"`
}

type Event struct {
	ID        string       `json:"id"`
	Type      EventType    `json:"type"`
	GameID    *string      `json:"gameID,omitempty"`
	RoomID    *string      `json:"roomID,omitempty"`
	Timestamp time.Time    `json:"timestamp"`
	Sequence  int32        `json:"sequence"`
	Payload   EventPayload `json:"payload,omitempty"`
}

type Game struct {
	ID        string        `json:"id"`
	RoomID    *string       `json:"roomId,omitempty"`
	Players   []*GamePlayer `json:"players"`
	Events    []*Event      `json:"events,omitempty"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

type GameCard struct {
	ID   string `json:"id"`
	Suit string `json:"suit"`
	Rank string `json:"rank"`
}

type GameEndedEventPayload struct {
	Winner      string       `json:"winner"`
	FinalScores []*TeamScore `json:"finalScores"`
	Teams       []*Team      `json:"teams,omitempty"`
}

func (GameEndedEventPayload) IsEventPayload() {}

type GamePlayer struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type GameScoreUpdatedEventPayload struct {
	Score []*TeamScore `json:"score"`
}

func (GameScoreUpdatedEventPayload) IsEventPayload() {}

type GameSnapshot struct {
	RoomID          string           `json:"roomId"`
	GameID          string           `json:"gameId"`
	Status          string           `json:"status"`
	TrumpSuit       *string          `json:"trumpSuit,omitempty"`
	CurrentPlayerID *string          `json:"currentPlayerId,omitempty"`
	MyHand          []*GameCard      `json:"myHand"`
	TablePlays      []*GameTablePlay `json:"tablePlays"`
	Teams           []*Team          `json:"teams"`
	Scores          []*TeamScore     `json:"scores"`
}

type GameStartedEventPayload struct {
	Teams []*Team `json:"teams,omitempty"`
}

func (GameStartedEventPayload) IsEventPayload() {}

type GameTablePlay struct {
	PlayerID string    `json:"playerId"`
	Card     *GameCard `json:"card"`
}

type JoinRoomInput struct {
	RoomID string `json:"roomId"`
	UserID string `json:"userId"`
}

type LeaveRoomInput struct {
	RoomID string `json:"roomId"`
	UserID string `json:"userId"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Player struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Type     PlayerType `json:"type"`
	Sequence int32      `json:"sequence"`
}

type PlayerJoinedEventPayload struct {
	PlayerID string `json:"playerId"`
	Name     string `json:"name"`
	Slot     int32  `json:"slot"`
}

func (PlayerJoinedEventPayload) IsEventPayload() {}

type PlayerLeftEventPayload struct {
	PlayerID string `json:"playerId"`
	RoomID   string `json:"roomId"`
}

func (PlayerLeftEventPayload) IsEventPayload() {}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Room struct {
	ID          string          `json:"id"`
	HostID      string          `json:"hostId"`
	Players     []*RoomPlayer   `json:"players"`
	Status      RoomStatus      `json:"status"`
	CreatedAt   time.Time       `json:"createdAt"`
	BotStrategy BotStrategyType `json:"botStrategy"`
}

type RoomClosedEventPayload struct {
	RoomID string `json:"roomId"`
}

func (RoomClosedEventPayload) IsEventPayload() {}

type RoomPlayer struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type RoundEndedEventPayload struct {
	WinnerTeam string       `json:"winnerTeam"`
	Score      []*TeamScore `json:"score"`
}

func (RoundEndedEventPayload) IsEventPayload() {}

type RoundStartedEventPayload struct {
	RoundNumber int32  `json:"roundNumber"`
	DealerID    string `json:"dealerId"`
}

func (RoundStartedEventPayload) IsEventPayload() {}

type StartGameInput struct {
	RoomID string `json:"roomId"`
}

type Team struct {
	ID      string    `json:"id"`
	Players []*Player `json:"players"`
}

type TeamScore struct {
	TeamID string `json:"teamId"`
	Points int32  `json:"points"`
}

type TrickEndedEventPayload struct {
	WinnerID string `json:"winnerId"`
	Points   int32  `json:"points"`
}

func (TrickEndedEventPayload) IsEventPayload() {}

type TrickStartedEventPayload struct {
	LeaderID string `json:"leaderId"`
}

func (TrickStartedEventPayload) IsEventPayload() {}

type TrumpRevealedEventPayload struct {
	Card *GameCard `json:"card"`
	Suit string    `json:"suit"`
}

func (TrumpRevealedEventPayload) IsEventPayload() {}

type TurnChangedEventPayload struct {
	PlayerID string `json:"playerId"`
}

func (TurnChangedEventPayload) IsEventPayload() {}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type UserStats struct {
	UserID string `json:"userId"`
	Games  int32  `json:"games"`
	Wins   int32  `json:"wins"`
	Elo    int32  `json:"elo"`
}

type BotStrategyType string

const (
	BotStrategyTypeEasy BotStrategyType = "EASY"
	BotStrategyTypeHard BotStrategyType = "HARD"
)

var AllBotStrategyType = []BotStrategyType{
	BotStrategyTypeEasy,
	BotStrategyTypeHard,
}

func (e BotStrategyType) IsValid() bool {
	switch e {
	case BotStrategyTypeEasy, BotStrategyTypeHard:
		return true
	}
	return false
}

func (e BotStrategyType) String() string {
	return string(e)
}

func (e *BotStrategyType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BotStrategyType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BotStrategyType", str)
	}
	return nil
}

func (e BotStrategyType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BotStrategyType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BotStrategyType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EventType string

const (
	EventTypeRoundStarted     EventType = "ROUND_STARTED"
	EventTypeTrickStarted     EventType = "TRICK_STARTED"
	EventTypeTrumpRevealed    EventType = "TRUMP_REVEALED"
	EventTypeCardDealt        EventType = "CARD_DEALT"
	EventTypeRoundEnded       EventType = "ROUND_ENDED"
	EventTypeGameScoreUpdated EventType = "GAME_SCORE_UPDATED"
	EventTypePlayerJoined     EventType = "PLAYER_JOINED"
	EventTypePlayerLeft       EventType = "PLAYER_LEFT"
	EventTypeGameStarted      EventType = "GAME_STARTED"
	EventTypeTurnChanged      EventType = "TURN_CHANGED"
	EventTypeCardPlayed       EventType = "CARD_PLAYED"
	EventTypeTrickEnded       EventType = "TRICK_ENDED"
	EventTypeGameEnded        EventType = "GAME_ENDED"
)

var AllEventType = []EventType{
	EventTypeRoundStarted,
	EventTypeTrickStarted,
	EventTypeTrumpRevealed,
	EventTypeCardDealt,
	EventTypeRoundEnded,
	EventTypeGameScoreUpdated,
	EventTypePlayerJoined,
	EventTypePlayerLeft,
	EventTypeGameStarted,
	EventTypeTurnChanged,
	EventTypeCardPlayed,
	EventTypeTrickEnded,
	EventTypeGameEnded,
}

func (e EventType) IsValid() bool {
	switch e {
	case EventTypeRoundStarted, EventTypeTrickStarted, EventTypeTrumpRevealed, EventTypeCardDealt, EventTypeRoundEnded, EventTypeGameScoreUpdated, EventTypePlayerJoined, EventTypePlayerLeft, EventTypeGameStarted, EventTypeTurnChanged, EventTypeCardPlayed, EventTypeTrickEnded, EventTypeGameEnded:
		return true
	}
	return false
}

func (e EventType) String() string {
	return string(e)
}

func (e *EventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventType", str)
	}
	return nil
}

func (e EventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlayerType string

const (
	PlayerTypeHuman PlayerType = "HUMAN"
	PlayerTypeBot   PlayerType = "BOT"
)

var AllPlayerType = []PlayerType{
	PlayerTypeHuman,
	PlayerTypeBot,
}

func (e PlayerType) IsValid() bool {
	switch e {
	case PlayerTypeHuman, PlayerTypeBot:
		return true
	}
	return false
}

func (e PlayerType) String() string {
	return string(e)
}

func (e *PlayerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerType", str)
	}
	return nil
}

func (e PlayerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoomStatus string

const (
	RoomStatusOpen   RoomStatus = "OPEN"
	RoomStatusInGame RoomStatus = "IN_GAME"
	RoomStatusClosed RoomStatus = "CLOSED"
)

var AllRoomStatus = []RoomStatus{
	RoomStatusOpen,
	RoomStatusInGame,
	RoomStatusClosed,
}

func (e RoomStatus) IsValid() bool {
	switch e {
	case RoomStatusOpen, RoomStatusInGame, RoomStatusClosed:
		return true
	}
	return false
}

func (e RoomStatus) String() string {
	return string(e)
}

func (e *RoomStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomStatus", str)
	}
	return nil
}

func (e RoomStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoomStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoomStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
