package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend/internal/graph/model"
	"context"
	"fmt"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.NewRoom) (*model.Room, error) {
	panic(fmt.Errorf("not implemented: CreateRoom - createRoom"))
}

// AddPlayer is the resolver for the addPlayer field.
func (r *mutationResolver) AddPlayer(ctx context.Context, roomID string, input model.NewPlayer) (*model.Room, error) {
	panic(fmt.Errorf("not implemented: AddPlayer - addPlayer"))
}

// RemovePlayer is the resolver for the removePlayer field.
func (r *mutationResolver) RemovePlayer(ctx context.Context, roomID string, playerID string) (*model.Room, error) {
	panic(fmt.Errorf("not implemented: RemovePlayer - removePlayer"))
}

// StartGame is the resolver for the startGame field.
func (r *mutationResolver) StartGame(ctx context.Context, input model.StartGameInput) (*model.Room, error) {
	panic(fmt.Errorf("not implemented: StartGame - startGame"))
}

// CloseRoom is the resolver for the closeRoom field.
func (r *mutationResolver) CloseRoom(ctx context.Context, roomID string) (bool, error) {
	panic(fmt.Errorf("not implemented: CloseRoom - closeRoom"))
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	panic(fmt.Errorf("not implemented: Rooms - rooms"))
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	panic(fmt.Errorf("not implemented: Room - room"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
