package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"backend/internal/domain"
	"backend/internal/graph/generated"
	"backend/internal/graph/model"
	"context"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.NewRoom) (*model.Room, error) {
	host := &domain.Player{
		ID:   input.HostID,
		Name: input.HostName,
		Type: domain.PlayerType(input.HostType),
	}

	room, err := r.RoomService.CreateRoom(input.RoomID, host)
	if err != nil {
		return nil, err
	}

	return mapRoom(room), nil
}

// AddPlayer is the resolver for the addPlayer field.
func (r *mutationResolver) AddPlayer(ctx context.Context, roomID string, input model.NewPlayer) (*model.Room, error) {
	player := &domain.Player{
		ID:   input.PlayerID,
		Name: input.Name,
		Type: domain.PlayerType(input.Type),
	}

	room, err := r.RoomService.AddPlayer(roomID, player)
	if err != nil {
		return nil, err
	}

	return mapRoom(room), nil
}

// RemovePlayer is the resolver for the removePlayer field.
func (r *mutationResolver) RemovePlayer(ctx context.Context, roomID string, playerID string) (*model.Room, error) {
	room, err := r.RoomService.RemovePlayer(roomID, playerID)
	if err != nil {
		return nil, err
	}

	return mapRoom(room), nil
}

// StartGame is the resolver for the startGame field.
func (r *mutationResolver) StartGame(ctx context.Context, input model.StartGameInput) (*model.Room, error) {
	room, err := r.RoomService.StartGame(input.RoomID, input.GameID)
	if err != nil {
		return nil, err
	}

	return mapRoom(room), nil
}

// CloseRoom is the resolver for the closeRoom field.
func (r *mutationResolver) CloseRoom(ctx context.Context, roomID string) (bool, error) {
	return r.RoomService.CloseRoom(roomID), nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	domainRooms := r.RoomService.GetRooms()

	rooms := []*model.Room{}

	for _, room := range domainRooms {
		rooms = append(rooms, mapRoom(room))
	}

	return rooms, nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	room, ok := r.RoomService.GetRoom(id)
	if !ok {
		return nil, nil
	}

	return mapRoom(room), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
