package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"backend/internal/infrastructure/graph/model"
	"context"
)

func (r *mutationResolver) CreateRoom(ctx context.Context, input model.CreateRoomInput) (*model.Room, error) {
	room, err := r.RoomService.CreateRoom(input.RoomID, input.HostID, input.HostName)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

func (r *mutationResolver) JoinRoom(ctx context.Context, input model.JoinRoomInput) (*model.Room, error) {
	room, err := r.RoomService.JoinRoom(input.RoomID, input.PlayerID, input.PlayerName)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

func (r *mutationResolver) LeaveRoom(ctx context.Context, input model.LeaveRoomInput) (*model.Room, error) {
	room, err := r.RoomService.LeaveRoom(input.RoomID, input.PlayerID)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

func (r *mutationResolver) StartGame(ctx context.Context, input model.StartGameInput) (*model.Room, error) {
	room, err := r.RoomService.StartGame(input.RoomID)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	room, err := r.RoomService.GetRoom(id)
	if err != nil || room == nil {
		return nil, err
	}
	return mapRoom(room), nil
}

func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	rooms, err := r.RoomService.GetRooms()
	if err != nil {
		return nil, err
	}

	result := make([]*model.Room, 0, len(rooms))
	for _, r := range rooms {
		result = append(result, mapRoom(r))
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
