package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"backend/internal/infrastructure/graph/model"
	"context"
)

// Events is the resolver for the events field.
func (r *gameResolver) Events(ctx context.Context, obj *model.Game) ([]*model.Event, error) {
	events, err := r.EventService.GetEventsByGameID(obj.ID)
	if err != nil {
		return nil, err
	}

	eventsResult := make([]*model.Event, 0, len(events))
	for _, e := range events {
		eventsResult = append(eventsResult, mapEvent(e))
	}
	return eventsResult, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	u, err := r.UserService.Register(input.Username, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		User: mapUser(u),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	u, err := r.UserService.Login(input.Username, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		User: mapUser(u),
	}, nil
}

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.CreateRoomInput) (*model.Room, error) {
	room, err := r.RoomService.CreateRoom(input.HostID)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

// JoinRoom is the resolver for the joinRoom field.
func (r *mutationResolver) JoinRoom(ctx context.Context, input model.JoinRoomInput) (*model.Room, error) {
	room, err := r.RoomService.JoinRoom(input.RoomID, input.UserID)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

// LeaveRoom is the resolver for the leaveRoom field.
func (r *mutationResolver) LeaveRoom(ctx context.Context, input model.LeaveRoomInput) (*model.Room, error) {
	room, err := r.RoomService.LeaveRoom(input.RoomID, input.UserID)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

// StartGame is the resolver for the startGame field.
func (r *mutationResolver) StartGame(ctx context.Context, input model.StartGameInput) (*model.Room, error) {
	room, err := r.RoomService.StartGame(input.RoomID)
	if err != nil {
		return nil, err
	}
	return mapRoom(room), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	u, err := r.UserService.GetUser(id)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	u, err := r.UserService.GetUserByUsername(username)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*model.Room, error) {
	room, err := r.RoomService.GetRoom(id)
	if err != nil || room == nil {
		return nil, err
	}
	return mapRoom(room), nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	rooms, err := r.RoomService.GetRooms()
	if err != nil {
		return nil, err
	}

	result := make([]*model.Room, 0, len(rooms))
	for _, r := range rooms {
		result = append(result, mapRoom(r))
	}

	return result, nil
}

// GameSnapshot is the resolver for the gameSnapshot field.
func (r *queryResolver) GameSnapshot(ctx context.Context, roomID string, playerID string) (*model.GameSnapshot, error) {
	snapshot, err := r.RoomService.GetGameSnapshot(roomID, playerID)
	if err != nil {
		return nil, err
	}
	return mapGameSnapshot(snapshot), nil
}

// UserStats is the resolver for the userStats field.
func (r *queryResolver) UserStats(ctx context.Context, userID string) (*model.UserStats, error) {
	userStats, err := r.UserStatsService.GetByUserID(userID)
	if err != nil {
		return nil, err
	}
	return mapUserStats(userStats), nil
}

// UserGames is the resolver for the userGames field.
func (r *queryResolver) UserGames(ctx context.Context, userID string) ([]*model.Game, error) {
	games, err := r.GameService.GetUserGames(userID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Game, 0, len(games))
	for _, g := range games {
		result = append(result, mapGame(g))
	}
	return result, nil
}

// Game returns GameResolver implementation.
func (r *Resolver) Game() GameResolver { return &gameResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type gameResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
