@startuml
title Diagrama de Estados - Game

[*] --> Starting

Starting : Criar jogo
Starting : Aguardar jogadores

Starting --> Playing : Jogo pronto para começar

Playing : Gerir rondas
Playing : Jogar cartas

Playing --> Finished : Todas as rondas terminadas

Finished --> [*]

@enduml